# Generated by Django 5.2.3 on 2025-06-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_autor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='foto',
        ),
    ]
