# Generated by Django 5.2.3 on 2025-06-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
