# Generated by Django 5.2.3 on 2025-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_image_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
