# Generated by Django 5.2.3 on 2025-06-11 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_alter_image_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nome',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
