# Generated by Django 5.2.3 on 2025-06-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_alter_image_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nome',
        ),
    ]
