# Generated by Django 5.2.3 on 2025-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_remove_image_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
